[package]
name = "ndtree-rust-c"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
rand="*"

[build-dependencies]
cc = "*"

[profile.release]
lto = true
codegen-units = 1
strip=true
panic = 'abort'

[profile.perf-debug]
inherits = "release"
debug=true
lto = true
strip=false
